### PR TITLE
Prepare release 2.4.0

### LINKED ISSUE #115: Package Upgrade issue
```
Because soundpool >=2.3.0 depends on soundpool_web ^2.2.0 which depends on http ^0.13.0, soundpool >=2.3.0 requires http ^0.13.0.
And because google_fonts >=4.0.5 depends on http ^1.0.0, soundpool >=2.3.0 is incompatible with google_fonts >=4.0.5.
So, because fecare depends on both google_fonts ^5.0.0 and soundpool ^2.3.0, version solving failed.
```

### PR DESCRIPTION
**Pull request by veloce**
Hi @ukasz123,  and many thanks for creating this package!

Please release a new version, as it prevents us to upgrade the `http` package. 🙏 

Resolves #115

### CODE REVIEW

**Comment by MrCsabaToth** [comment]
Please merge

**Comment by MrCsabaToth** [comment]
Can also be https://github.com/ukasz123/soundpool/issues/121 in it? (It's 3 lines in the build.gradle)

**Comment by donghak-medi** [comment]
Please merge

**Comment by yelkamel** [comment]
When this will be merged ?

**Review by ukasz123 — APPROVED** [review]

**Pull request merged**
